version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    container_name: task-manager
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  database:
    image: postgres
    container_name: pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
