version: "3.9"

services:
  app:
    image: okerdocker11/task-manager:1.2.0-dev
#    build:
#      dockerfile: Dockerfile
#      context: .
#      target: dev
    container_name: task-manager
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"


  db:
    image: postgres
    container_name: pgdb
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres_data:
